import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import React from "react";
import { ThemeProvider } from "../components/ThemeProvider"
const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Skin Canvas Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} mx-auto max-w-[1920px]`}>
      <ThemeProvider attribute="class" defaultTheme="system">
        <Navbar />
        {children}
        <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
